language: ruby
rvm:
- 2.3.3
install: gem install jekyll
script:
- jekyll build
exclude:
- vendor
deploy:
  provider: s3
  access_key_id: AKIAIY6O7BIEETVHSPNA
  secret_access_key:
    secure: 1Yw7MyJi6NxizkqmYcGH6wKD+U1XTvfZVnTbYNdSaDJmlEtUSpZ1NP5uvk4GiRKNQgKDJBhjgf8THleY3Z2PulT9c6noBRiibl3sY8ddWkdJYhn5YfoUYPNfEfpC37YHz3AzHs8NlRBaP5X/EtgbqdszbWlE9SceiJV8/LrnsK7idPnnvlk30sHIj4pnYtNdsCn1t78TxQRb+dSno12KaUlD2pBoaYGgEFdkK74C5BL8cYDrtwN8Wy4uImeo8AfLptBLXUWnMfqU52awaXbR3uAmYWtMyc5EvjAnJuv39aZVfwaZ762QlgrB3t6Jbe468K7HAlFHdlywsF7TrB0wh4Pl4b2TbYpA0a9fpQMjQtBDqC0qhcL9rNIB2m15znxbFUrXmuwJbJuIgyFTVasnEkkJ0d0WgDs0T2CqchXbq6gXvqJ0fQhMVceJMtoag2Zt5EyDfBdPKSbHskXJxVwuIMl1Tg1BgqggehPpBy258+ZqkuHUpDGK/2sNoXpxzEt4zgOjtV17vaxb9k0y7ecOV7v8hnCkM1QaXHbKaUm6R8KT00jch+BGU2+0zxEL5HOBfL3DLz5IL+4uhVT8jHj1V86rHk0xti3JVGEI3AHVmou76UOw3RpPwjeZZ/dt35kF25NJvwSFL4N+pqdmGNN++FBGSl7q8SrTPzF2PCm7Is0=
  bucket: snaphole.io
  skip_cleanup: true
  local-dir: _site
  acl: public_read
  on:
    repo: YOWCT/SnapHole-AppStore
