language: ruby
rvm:
- 2.3.3
install: gem install jekyll html-proofer
script:
  - jekyll build
  # - htmlproofer ./_site
exclude: [vendor]
deploy:
  provider: s3
  access_key_id: AKIAJI5JIE7VOK4DJS2A
  secret_access_key: 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
  bucket: snaphole.io
  region: us-east-1
  acl: public_read
  skip_cleanup: true
  local-dir: _site
