language: ruby
rvm:
- 2.3.3
install: gem install jekyll
script:
- jekyll build
exclude:
- vendor
deploy:
  provider: s3
  access_key_id: AKIAJI5JIE7VOK4DJS2A
  secret_access_key:
    secure: WSZwKKrl1HJPP517J2oZtqo7qh+FRUA0ZvlFqMxNO55xkgb++P3k3K3WMbvHpOY8bDZWveqSA3trzneNbXOkJ+agonP1ErkzNoC8hNqdP9GFxerKiGSGXPK1RLiZBCjV5p/Gi8cHUhEdMnj6/DjCQ2MRG89Y5nRfW+d1YLOzrtd+b8KHUvfDRplxM7wXzTMr2tKzusRkHrtuDu45jCOE9ht8XhVo1jl8N6ntUqq9ouPd3GX6W0NRMgWsVjkClye7s0HLM7nyo7Tp2JmkHPBKPS8+QV4ZFLgQr31d+vheXkFSRWrViws91ULVSA1GKpbIZJ0PBtcb5MZBZkwbm2+LRCeGslyk9uzYpd+aBFf8KgdhBDZxx2kr1RFDrbMJRJ6XJBjYv/pTh1R9q6ShifhEStjkzPxJgrPW3K3rCsehC8vmGn7I0xfucugH3Hl1Fsrx4GRIK0iEzqWVyNkapZ3zSm2P4eRvXTptZD8Ftf0IItYCBSXRTSjxvs+wY9g7oyxqsmuc4MJS05g4tbLuMb2n/ZyvjCemw8WxZ5WCEscV0SiTcWjFO6UG1wv67LaA9WVSt+aPpINU+TkUImmGv+4R1lipTynym2Zl0TOLhNu1AhkFNDeEse4qey9uBqma139vAsGh1Ip0qvHjtL9VY/tqbJHxVpzGet398nR2Zb9xQvo=
  bucket: snaphole.io
  skip_cleanup: true
  local-dir: _site
  acl: public_read
  on:
    repo: YOWCT/SnapHole-AppStore
